server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

## H2Database Config
spring:
  profiles:
    active: release

  datasource:
    url: jdbc:mysql://database-1.cumccqsvb60h.ap-northeast-2.rds.amazonaws.com:3306/jupjup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ksh03050621
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: none
    show-sql: true
    generate-ddl: true
    database: mysql

  messages:
    basename: i18n/exception	
    encoding: UTF-8

  jwt:
    secret: goelepel@%&*(&(*&()^%&^*jhadsklfh*&^*&(^ds8af76(*&^ads8fsadf879asd6f*(A&^AFSads987f6asd897f6(*&ASF^ads9876fsad897f6(A*&SF^ads897fg6asd9f876*(&AFS^ads987gf6adfs8976

# Gmail SMTP Server Settings
  mail:
    host: smtp.googlemail.com
    port: 587
    username: webtechnologiesofficial@gmail.com
    password: wnqwnqdhvltuf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #Redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
#AWS
cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      access-key: AKIAUFJW3PBKUF7BZD5I
      secret-key: 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
    stack:
      auto: false

    s3:
      bucket: jupjupapplication
      stack:
        auto: false
      credentials:
        instanceProfile: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
